version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo Build started
      - mvn clean install -DskipTests=true
artifacts:
  files:
    - target/personalkanbanboardbackend-0.0.1-SNAPSHOT.jar
    - aws/ec2-scripts/*.sh
    - appspec.yml
  discard-paths: yes
