version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kanban_board
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:8.4
    restart: always
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8000:80"
