spring:
  application:
    name: personal-kanban-board-backend
  graphql:
    graphiql:
      enabled: true
  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5432/kanban_board
  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/kanban_board
    locations: classpath:db/migration/postgres
app:
  jwt:
    secret-key: 8f9879e8-1afd-4a88-81b8-04d68f32fdaf-test
    expiration-time-in-milliseconds: 10800000
    authorization-header: Authorization
    authorization-type: Bearer
    authorization-header-start-index: 7
