spring:
  application:
    name: personal-kanban-board-backend
  graphql:
    graphiql:
      enabled: true
  r2dbc:
    username: ${DB_USERNAME:postgress}
    password: ${DB_PASSWORD:postgress}
    url: r2dbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:kanban_board}
  flyway:
    user: ${DB_USERNAME:postgress}
    password: ${DB_PASSWORD:postgress}
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:kanban_board}
    locations: classpath:db/migration/postgres

logging.file.path: .

app:
  jwt:
    secret-key: 8f9879e8-1afd-4a88-81b8-04d68f32fdaf-test
    expiration-time-in-milliseconds: 10800000
    authorization-header: Authorization
    authorization-type: Bearer
    authorization-header-start-index: 7
