spring:
  graphql:
    cors:
      allow-credentials: true
      allowed-origins:
        - http://localhost:4200
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
    show-sql: true
